[package]
name = "trt"
version = "0.3.0"
authors = ["Afnan Enayet <afnan.enayet@gmail.com>"]

[lib]
name = "trtlib"
path = "src/lib.rs"
doc = true

[[bin]]
name = "trt"
path = "src/main.rs"
doc = false

[dependencies]
image = "0.20.0"
nalgebra = "0.16.4"
pbr = "1.0.1"
rand = "0.5.5"
num = "0.2.0"
rayon = "1.0.2"

[dependencies.nalgebra-lapack]
version = "0.8.0"
default-features = false
# features = [ "Accelerate" ]

[profile.release]
opt-level = 3
debug = false
