[package]
name = "trt"
version = "0.1.0"
authors = ["Afnan Enayet <afnan.enayet@gmail.com>"]

[lib]
name = "trtlib"
path = "src/lib.rs"
doc = true

[[bin]]
name = "trt"
path = "src/main.rs"
doc = false

[dependencies]
image = "0.19.0"
nalgebra = "0.15.2"
pbr = "1.0.1"
rand = "0.5.1"
num = "0.1.42"
rayon = "1.0.1"

[profile.release]
opt-level = 3
debug = false
rpath = false
