[package]
name = "trt"
version = "0.1.0"
authors = ["Afnan Enayet <afnan.enayet@gmail.com>"]

[lib]
name = "trtlib"
path = "src/lib.rs"
doc = true

[[bin]]
name = "trt"
path = "src/main.rs"
doc = false

[dependencies]
image = "0.19.0"
nalgebra = "0.15.2"
pbr = "1.0.1"

# set up linear algebra acceleration
# user must set their own acceleration library
[dependencies.nalgebra-lapack]
version = "0.5"
default-features = false

# TODO: update this to use whatever library is best for your platform
features = ["accelerate"]

[profile.release]
opt-level = 3
debug = false
rpath = false
