[package]
name = "trt"
version = "0.1.0"
authors = ["Afnan Enayet <afnan.enayet@gmail.com>"]

[lib]
name = "trtlib"
path = "src/lib.rs"
doc = true

[[bin]]
name = "trt"
path = "src/main.rs"
doc = false

[dependencies]
image = "0.19.0"
nalgebra = "0.15.2"
