[package]
name = "trt"
version = "0.5.0"
authors = ["Afnan Enayet <afnan@afnan.io>"]
edition = "2018"

[lib]
name = "trtlib"
path = "src/lib.rs"
doc = true

[[bin]]
name = "trt"
path = "src/main.rs"
doc = false

[dependencies]
image = "0.20.1"
nalgebra = "0.16.13"
indicatif = "0.11.0"
rand = "0.6.1"
num = "0.2.0"
rayon = "1.0.3"
clap = {version = "2.32.0", features = ["yaml", "suggestions", "color"]}

[dependencies.nalgebra-lapack]
version = "0.8.0"
default-features = false
# features = ["accelerate"]

[profile.release]
lto = true
opt-level = 3
debug = false
panic = "abort"
codegen-units = 1
